/**
 * Complete metadata for all 66 books of the KJV Bible.
 * Includes category, author, date_written, description, key_themes.
 */

export interface BookMeta {
  name: string;
  abbreviation: string;
  testament: "OT" | "NT";
  category: string;
  chapterCount: number;
  author: string;
  dateWritten: string;
  description: string;
  keyThemes: string;
  sortOrder: number;
}

export const BOOK_METADATA: BookMeta[] = [
  // ─── Old Testament: Law (Torah/Pentateuch) ─────────────────
  {
    name: "Genesis",
    abbreviation: "Gen",
    testament: "OT",
    category: "Law",
    chapterCount: 50,
    author: "Moses",
    dateWritten: "c. 1445–1405 BC",
    description:
      "The book of beginnings: creation, the fall of man, the flood, and the patriarchs Abraham, Isaac, Jacob, and Joseph.",
    keyThemes: "Creation, Fall, Covenant, Faith, Providence",
    sortOrder: 1,
  },
  {
    name: "Exodus",
    abbreviation: "Exod",
    testament: "OT",
    category: "Law",
    chapterCount: 40,
    author: "Moses",
    dateWritten: "c. 1445–1405 BC",
    description:
      "Israel's deliverance from Egyptian bondage, the giving of the Law at Sinai, and the construction of the tabernacle.",
    keyThemes: "Deliverance, Law, Worship, Covenant, God's Presence",
    sortOrder: 2,
  },
  {
    name: "Leviticus",
    abbreviation: "Lev",
    testament: "OT",
    category: "Law",
    chapterCount: 27,
    author: "Moses",
    dateWritten: "c. 1445–1405 BC",
    description:
      "Laws and regulations for worship, sacrifices, and holy living given to the Levitical priesthood.",
    keyThemes: "Holiness, Sacrifice, Atonement, Purity, Priesthood",
    sortOrder: 3,
  },
  {
    name: "Numbers",
    abbreviation: "Num",
    testament: "OT",
    category: "Law",
    chapterCount: 36,
    author: "Moses",
    dateWritten: "c. 1445–1405 BC",
    description:
      "Israel's wilderness wanderings, census records, and the consequences of disobedience during the journey to the Promised Land.",
    keyThemes: "Faithfulness, Discipline, Wandering, God's Patience, Obedience",
    sortOrder: 4,
  },
  {
    name: "Deuteronomy",
    abbreviation: "Deut",
    testament: "OT",
    category: "Law",
    chapterCount: 34,
    author: "Moses",
    dateWritten: "c. 1445–1405 BC",
    description:
      "Moses' farewell speeches to Israel, restating the Law and renewing the covenant before entering the Promised Land.",
    keyThemes: "Covenant Renewal, Obedience, Blessings, Love for God, Remembrance",
    sortOrder: 5,
  },

  // ─── Old Testament: History ────────────────────────────────
  {
    name: "Joshua",
    abbreviation: "Josh",
    testament: "OT",
    category: "History",
    chapterCount: 24,
    author: "Joshua",
    dateWritten: "c. 1400–1370 BC",
    description:
      "The conquest and division of the Promised Land under Joshua's leadership after the death of Moses.",
    keyThemes: "Conquest, Faith, Obedience, Promise Fulfillment, Leadership",
    sortOrder: 6,
  },
  {
    name: "Judges",
    abbreviation: "Judg",
    testament: "OT",
    category: "History",
    chapterCount: 21,
    author: "Samuel",
    dateWritten: "c. 1050–1000 BC",
    description:
      "The cyclical pattern of Israel's disobedience, oppression, repentance, and deliverance through judges raised by God.",
    keyThemes: "Cycle of Sin, Deliverance, Faithlessness, God's Mercy, Moral Decline",
    sortOrder: 7,
  },
  {
    name: "Ruth",
    abbreviation: "Ruth",
    testament: "OT",
    category: "History",
    chapterCount: 4,
    author: "Samuel",
    dateWritten: "c. 1050–1000 BC",
    description:
      "A beautiful story of loyalty and redemption: Ruth's devotion to Naomi and her marriage to Boaz, a kinsman-redeemer.",
    keyThemes: "Loyalty, Redemption, Providence, Kindness, Ancestry of David",
    sortOrder: 8,
  },
  {
    name: "1 Samuel",
    abbreviation: "1Sam",
    testament: "OT",
    category: "History",
    chapterCount: 31,
    author: "Samuel, Nathan, Gad",
    dateWritten: "c. 1050–930 BC",
    description:
      "The transition from judges to kings: Samuel's ministry, Saul's rise and fall, and David's anointing.",
    keyThemes: "Leadership, Obedience, Kingship, Heart of God, Rejection",
    sortOrder: 9,
  },
  {
    name: "2 Samuel",
    abbreviation: "2Sam",
    testament: "OT",
    category: "History",
    chapterCount: 24,
    author: "Nathan, Gad",
    dateWritten: "c. 1050–930 BC",
    description:
      "David's reign as king over Israel, including his triumphs, his sin with Bathsheba, and its consequences.",
    keyThemes: "Davidic Covenant, Consequences of Sin, Grace, Sovereignty, Worship",
    sortOrder: 10,
  },
  {
    name: "1 Kings",
    abbreviation: "1Kgs",
    testament: "OT",
    category: "History",
    chapterCount: 22,
    author: "Jeremiah (tradition)",
    dateWritten: "c. 560–540 BC",
    description:
      "Solomon's glorious reign, the building of the temple, the divided kingdom, and the prophet Elijah's ministry.",
    keyThemes: "Wisdom, Temple, Division, Idolatry, Prophetic Witness",
    sortOrder: 11,
  },
  {
    name: "2 Kings",
    abbreviation: "2Kgs",
    testament: "OT",
    category: "History",
    chapterCount: 25,
    author: "Jeremiah (tradition)",
    dateWritten: "c. 560–540 BC",
    description:
      "The decline and fall of both Israel and Judah, Elisha's ministry, and the Babylonian exile.",
    keyThemes: "Judgment, Exile, Prophetic Warning, Faithfulness, Consequences",
    sortOrder: 12,
  },
  {
    name: "1 Chronicles",
    abbreviation: "1Chr",
    testament: "OT",
    category: "History",
    chapterCount: 29,
    author: "Ezra (tradition)",
    dateWritten: "c. 450–425 BC",
    description:
      "Genealogies from Adam to David and David's reign, emphasizing worship and the temple preparations.",
    keyThemes: "Genealogy, Worship, Temple, Davidic Line, Faithfulness",
    sortOrder: 13,
  },
  {
    name: "2 Chronicles",
    abbreviation: "2Chr",
    testament: "OT",
    category: "History",
    chapterCount: 36,
    author: "Ezra (tradition)",
    dateWritten: "c. 450–425 BC",
    description:
      "Solomon's temple and the history of Judah's kings, emphasizing faithfulness to God and temple worship.",
    keyThemes: "Temple Worship, Revival, Faithfulness, Judgment, Prayer",
    sortOrder: 14,
  },
  {
    name: "Ezra",
    abbreviation: "Ezra",
    testament: "OT",
    category: "History",
    chapterCount: 10,
    author: "Ezra",
    dateWritten: "c. 450–420 BC",
    description:
      "The return of Jewish exiles from Babylon, the rebuilding of the temple, and spiritual reforms.",
    keyThemes: "Restoration, Rebuilding, Repentance, God's Faithfulness, Separation",
    sortOrder: 15,
  },
  {
    name: "Nehemiah",
    abbreviation: "Neh",
    testament: "OT",
    category: "History",
    chapterCount: 13,
    author: "Nehemiah",
    dateWritten: "c. 445–420 BC",
    description:
      "The rebuilding of Jerusalem's walls under Nehemiah's leadership and the spiritual renewal of the people.",
    keyThemes: "Rebuilding, Leadership, Prayer, Renewal, Perseverance",
    sortOrder: 16,
  },
  {
    name: "Esther",
    abbreviation: "Esth",
    testament: "OT",
    category: "History",
    chapterCount: 10,
    author: "Unknown (possibly Mordecai)",
    dateWritten: "c. 470–424 BC",
    description:
      "Queen Esther's courageous intervention to save the Jewish people from genocide in the Persian Empire.",
    keyThemes: "Providence, Courage, Deliverance, Identity, Sovereignty",
    sortOrder: 17,
  },

  // ─── Old Testament: Poetry (Wisdom Literature) ────────────
  {
    name: "Job",
    abbreviation: "Job",
    testament: "OT",
    category: "Poetry",
    chapterCount: 42,
    author: "Unknown (possibly Job, Moses, or Solomon)",
    dateWritten: "c. 2000–1500 BC",
    description:
      "The profound story of Job's suffering, his friends' debates about the cause, and God's sovereign response.",
    keyThemes: "Suffering, Sovereignty, Faith, Wisdom, Restoration",
    sortOrder: 18,
  },
  {
    name: "Psalms",
    abbreviation: "Ps",
    testament: "OT",
    category: "Poetry",
    chapterCount: 150,
    author: "David, Asaph, Sons of Korah, and others",
    dateWritten: "c. 1410–450 BC",
    description:
      "The hymnbook of Israel: 150 poems and songs of praise, lament, thanksgiving, and wisdom.",
    keyThemes: "Worship, Praise, Lament, Trust, Messianic Prophecy",
    sortOrder: 19,
  },
  {
    name: "Proverbs",
    abbreviation: "Prov",
    testament: "OT",
    category: "Poetry",
    chapterCount: 31,
    author: "Solomon, Agur, Lemuel",
    dateWritten: "c. 970–700 BC",
    description:
      "A collection of wise sayings and instructions for practical, godly living in everyday situations.",
    keyThemes: "Wisdom, Fear of the Lord, Discipline, Righteousness, Prudence",
    sortOrder: 20,
  },
  {
    name: "Ecclesiastes",
    abbreviation: "Eccl",
    testament: "OT",
    category: "Poetry",
    chapterCount: 12,
    author: "Solomon",
    dateWritten: "c. 940–930 BC",
    description:
      "A philosophical exploration of life's meaning, concluding that all is vanity apart from fearing God.",
    keyThemes: "Vanity, Meaning of Life, Wisdom, Time, Fear of God",
    sortOrder: 21,
  },
  {
    name: "Song of Solomon",
    abbreviation: "Song",
    testament: "OT",
    category: "Poetry",
    chapterCount: 8,
    author: "Solomon",
    dateWritten: "c. 970–930 BC",
    description:
      "A lyrical celebration of love between a bridegroom and his bride, often interpreted as an allegory of divine love.",
    keyThemes: "Love, Beauty, Devotion, Intimacy, Faithfulness",
    sortOrder: 22,
  },

  // ─── Old Testament: Major Prophets ────────────────────────
  {
    name: "Isaiah",
    abbreviation: "Isa",
    testament: "OT",
    category: "Major Prophets",
    chapterCount: 66,
    author: "Isaiah",
    dateWritten: "c. 740–680 BC",
    description:
      "Prophecies of judgment and consolation, including the Suffering Servant and the coming Messiah.",
    keyThemes: "Holiness, Judgment, Salvation, Messianic Prophecy, Comfort",
    sortOrder: 23,
  },
  {
    name: "Jeremiah",
    abbreviation: "Jer",
    testament: "OT",
    category: "Major Prophets",
    chapterCount: 52,
    author: "Jeremiah",
    dateWritten: "c. 627–585 BC",
    description:
      "The weeping prophet's warnings of Jerusalem's destruction and promises of a new covenant.",
    keyThemes: "Judgment, Repentance, New Covenant, Faithfulness, Suffering",
    sortOrder: 24,
  },
  {
    name: "Lamentations",
    abbreviation: "Lam",
    testament: "OT",
    category: "Major Prophets",
    chapterCount: 5,
    author: "Jeremiah",
    dateWritten: "c. 586 BC",
    description:
      "Five poems of mourning over the destruction of Jerusalem and the temple by Babylon.",
    keyThemes: "Mourning, Judgment, Hope, God's Faithfulness, Suffering",
    sortOrder: 25,
  },
  {
    name: "Ezekiel",
    abbreviation: "Ezek",
    testament: "OT",
    category: "Major Prophets",
    chapterCount: 48,
    author: "Ezekiel",
    dateWritten: "c. 593–571 BC",
    description:
      "Visions and prophecies from Babylonian exile, including the valley of dry bones and the future temple.",
    keyThemes: "God's Glory, Judgment, Restoration, Visions, Sovereignty",
    sortOrder: 26,
  },
  {
    name: "Daniel",
    abbreviation: "Dan",
    testament: "OT",
    category: "Major Prophets",
    chapterCount: 12,
    author: "Daniel",
    dateWritten: "c. 536–530 BC",
    description:
      "Daniel's faithfulness in Babylonian captivity and apocalyptic visions of future kingdoms and God's eternal reign.",
    keyThemes: "Faithfulness, Sovereignty, Prophecy, Kingdoms, Apocalyptic Vision",
    sortOrder: 27,
  },

  // ─── Old Testament: Minor Prophets ────────────────────────
  {
    name: "Hosea",
    abbreviation: "Hos",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 14,
    author: "Hosea",
    dateWritten: "c. 755–710 BC",
    description:
      "God's unfailing love illustrated through Hosea's marriage to unfaithful Gomer, a picture of Israel's spiritual adultery.",
    keyThemes: "Unfailing Love, Spiritual Adultery, Repentance, Restoration, Covenant",
    sortOrder: 28,
  },
  {
    name: "Joel",
    abbreviation: "Joel",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 3,
    author: "Joel",
    dateWritten: "c. 835–800 BC",
    description:
      "A locust plague as a warning of the Day of the Lord and the promise of the Spirit's outpouring.",
    keyThemes: "Day of the Lord, Repentance, Spirit Outpouring, Judgment, Restoration",
    sortOrder: 29,
  },
  {
    name: "Amos",
    abbreviation: "Amos",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 9,
    author: "Amos",
    dateWritten: "c. 760–750 BC",
    description:
      "A shepherd-prophet's call for justice and righteousness against Israel's social oppression and religious hypocrisy.",
    keyThemes: "Justice, Righteousness, Social Oppression, Judgment, God's Sovereignty",
    sortOrder: 30,
  },
  {
    name: "Obadiah",
    abbreviation: "Obad",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 1,
    author: "Obadiah",
    dateWritten: "c. 586–553 BC",
    description:
      "The shortest Old Testament book: a prophecy of judgment against Edom for their pride and hostility toward Israel.",
    keyThemes: "Pride, Judgment, Brotherhood, Justice, God's Kingdom",
    sortOrder: 31,
  },
  {
    name: "Jonah",
    abbreviation: "Jonah",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 4,
    author: "Jonah",
    dateWritten: "c. 785–760 BC",
    description:
      "The reluctant prophet's flight from God, miraculous deliverance, and preaching to Nineveh.",
    keyThemes: "Compassion, Obedience, Repentance, God's Mercy, Mission",
    sortOrder: 32,
  },
  {
    name: "Micah",
    abbreviation: "Mic",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 7,
    author: "Micah",
    dateWritten: "c. 735–700 BC",
    description:
      "Prophecies of judgment and hope, including the birthplace of the Messiah in Bethlehem.",
    keyThemes: "Justice, Mercy, Humility, Messianic Prophecy, Hope",
    sortOrder: 33,
  },
  {
    name: "Nahum",
    abbreviation: "Nah",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 3,
    author: "Nahum",
    dateWritten: "c. 663–612 BC",
    description:
      "A prophecy of Nineveh's destruction, demonstrating God's justice against the oppressive Assyrian Empire.",
    keyThemes: "God's Justice, Judgment, Sovereignty, Vengeance, Comfort for the Oppressed",
    sortOrder: 34,
  },
  {
    name: "Habakkuk",
    abbreviation: "Hab",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 3,
    author: "Habakkuk",
    dateWritten: "c. 612–589 BC",
    description:
      "A prophet's dialogue with God about injustice, culminating in a hymn of faith despite suffering.",
    keyThemes: "Faith, Justice, Sovereignty, Trust, Living by Faith",
    sortOrder: 35,
  },
  {
    name: "Zephaniah",
    abbreviation: "Zeph",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 3,
    author: "Zephaniah",
    dateWritten: "c. 640–621 BC",
    description:
      "Warnings of the Day of the Lord's judgment and promises of restoration for a faithful remnant.",
    keyThemes: "Day of the Lord, Judgment, Remnant, Restoration, Joy",
    sortOrder: 36,
  },
  {
    name: "Haggai",
    abbreviation: "Hag",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 2,
    author: "Haggai",
    dateWritten: "c. 520 BC",
    description:
      "A call to the returned exiles to rebuild the temple and put God first in their priorities.",
    keyThemes: "Priorities, Temple Rebuilding, Obedience, God's Presence, Encouragement",
    sortOrder: 37,
  },
  {
    name: "Zechariah",
    abbreviation: "Zech",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 14,
    author: "Zechariah",
    dateWritten: "c. 520–480 BC",
    description:
      "Apocalyptic visions encouraging the rebuilding of the temple, with rich Messianic prophecies.",
    keyThemes: "Messianic Prophecy, Visions, Restoration, God's Sovereignty, Hope",
    sortOrder: 38,
  },
  {
    name: "Malachi",
    abbreviation: "Mal",
    testament: "OT",
    category: "Minor Prophets",
    chapterCount: 4,
    author: "Malachi",
    dateWritten: "c. 440–430 BC",
    description:
      "The final Old Testament prophet confronts spiritual apathy and points to the coming messenger.",
    keyThemes: "Covenant Faithfulness, Tithing, Coming Messenger, Judgment, Repentance",
    sortOrder: 39,
  },

  // ─── New Testament: Gospels ───────────────────────────────
  {
    name: "Matthew",
    abbreviation: "Matt",
    testament: "NT",
    category: "Gospels",
    chapterCount: 28,
    author: "Matthew (Levi)",
    dateWritten: "c. AD 55–65",
    description:
      "The Gospel written for a Jewish audience, presenting Jesus as the promised Messiah and King of Israel.",
    keyThemes: "Messiahship, Kingdom of Heaven, Fulfillment of Prophecy, Discipleship, Teaching",
    sortOrder: 40,
  },
  {
    name: "Mark",
    abbreviation: "Mark",
    testament: "NT",
    category: "Gospels",
    chapterCount: 16,
    author: "John Mark",
    dateWritten: "c. AD 55–65",
    description:
      "The shortest Gospel, emphasizing Jesus as the Suffering Servant through fast-paced narrative of His deeds.",
    keyThemes: "Suffering Servant, Authority, Discipleship, Sacrifice, Immediacy",
    sortOrder: 41,
  },
  {
    name: "Luke",
    abbreviation: "Luke",
    testament: "NT",
    category: "Gospels",
    chapterCount: 24,
    author: "Luke",
    dateWritten: "c. AD 58–63",
    description:
      "A carefully researched account presenting Jesus as the Son of Man who came to seek and save the lost.",
    keyThemes: "Compassion, Son of Man, Salvation for All, Prayer, Holy Spirit",
    sortOrder: 42,
  },
  {
    name: "John",
    abbreviation: "John",
    testament: "NT",
    category: "Gospels",
    chapterCount: 21,
    author: "John (the Apostle)",
    dateWritten: "c. AD 85–95",
    description:
      "A theological Gospel presenting Jesus as the eternal Word of God, the divine Son, through seven signs and seven 'I am' statements.",
    keyThemes: "Deity of Christ, Belief, Eternal Life, Light, Love",
    sortOrder: 43,
  },

  // ─── New Testament: History ───────────────────────────────
  {
    name: "Acts",
    abbreviation: "Acts",
    testament: "NT",
    category: "History",
    chapterCount: 28,
    author: "Luke",
    dateWritten: "c. AD 63–64",
    description:
      "The birth and spread of the early church from Jerusalem to Rome, empowered by the Holy Spirit.",
    keyThemes: "Holy Spirit, Church Growth, Mission, Persecution, Gospel Expansion",
    sortOrder: 44,
  },

  // ─── New Testament: Pauline Epistles ──────────────────────
  {
    name: "Romans",
    abbreviation: "Rom",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 16,
    author: "Paul",
    dateWritten: "c. AD 57",
    description:
      "Paul's systematic presentation of the Gospel: justification by faith, sanctification, and the relationship of Jews and Gentiles.",
    keyThemes: "Justification, Faith, Grace, Righteousness, Sanctification",
    sortOrder: 45,
  },
  {
    name: "1 Corinthians",
    abbreviation: "1Cor",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 16,
    author: "Paul",
    dateWritten: "c. AD 55",
    description:
      "Paul addresses divisions, immorality, and doctrinal issues in the Corinthian church, including love and resurrection.",
    keyThemes: "Unity, Love, Spiritual Gifts, Resurrection, Church Order",
    sortOrder: 46,
  },
  {
    name: "2 Corinthians",
    abbreviation: "2Cor",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 13,
    author: "Paul",
    dateWritten: "c. AD 55–56",
    description:
      "Paul's most personal letter, defending his apostleship and teaching about strength in weakness.",
    keyThemes: "Comfort, Weakness and Strength, Ministry, Generosity, Reconciliation",
    sortOrder: 47,
  },
  {
    name: "Galatians",
    abbreviation: "Gal",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 6,
    author: "Paul",
    dateWritten: "c. AD 49–55",
    description:
      "A passionate defense of justification by faith alone against those requiring Gentile adherence to the Law.",
    keyThemes: "Freedom, Justification by Faith, Law vs. Grace, Spirit, Liberty",
    sortOrder: 48,
  },
  {
    name: "Ephesians",
    abbreviation: "Eph",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 6,
    author: "Paul",
    dateWritten: "c. AD 60–62",
    description:
      "A letter on the nature of the church as the body of Christ and practical instructions for Christian living.",
    keyThemes: "Church as Body, Unity, Grace, Spiritual Warfare, New Identity",
    sortOrder: 49,
  },
  {
    name: "Philippians",
    abbreviation: "Phil",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 4,
    author: "Paul",
    dateWritten: "c. AD 61–62",
    description:
      "A joyful letter from prison encouraging the Philippians to find joy in Christ regardless of circumstances.",
    keyThemes: "Joy, Humility, Contentment, Christ's Example, Unity",
    sortOrder: 50,
  },
  {
    name: "Colossians",
    abbreviation: "Col",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 4,
    author: "Paul",
    dateWritten: "c. AD 60–62",
    description:
      "Paul combats false teaching by proclaiming Christ's supremacy over all creation and every spiritual power.",
    keyThemes: "Supremacy of Christ, Fullness, Freedom from Legalism, New Life, Wisdom",
    sortOrder: 51,
  },
  {
    name: "1 Thessalonians",
    abbreviation: "1Thess",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 5,
    author: "Paul",
    dateWritten: "c. AD 51",
    description:
      "Encouragement to a young church and teaching about the return of Christ and holy living.",
    keyThemes: "Second Coming, Hope, Holiness, Encouragement, Faithfulness",
    sortOrder: 52,
  },
  {
    name: "2 Thessalonians",
    abbreviation: "2Thess",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 3,
    author: "Paul",
    dateWritten: "c. AD 51–52",
    description:
      "Further teaching about the Day of the Lord and encouragement to persevere in faith and work.",
    keyThemes: "Day of the Lord, Perseverance, Work Ethic, Man of Lawlessness, Encouragement",
    sortOrder: 53,
  },
  {
    name: "1 Timothy",
    abbreviation: "1Tim",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 6,
    author: "Paul",
    dateWritten: "c. AD 62–64",
    description:
      "Pastoral instructions to Timothy on church leadership, sound doctrine, and godly conduct.",
    keyThemes: "Church Leadership, Sound Doctrine, Godliness, Pastoral Care, False Teaching",
    sortOrder: 54,
  },
  {
    name: "2 Timothy",
    abbreviation: "2Tim",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 4,
    author: "Paul",
    dateWritten: "c. AD 66–67",
    description:
      "Paul's final letter, a deeply personal charge to Timothy to guard the gospel and endure hardship.",
    keyThemes: "Endurance, Faithfulness, Scripture, Legacy, Courage",
    sortOrder: 55,
  },
  {
    name: "Titus",
    abbreviation: "Titus",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 3,
    author: "Paul",
    dateWritten: "c. AD 63–65",
    description:
      "Instructions to Titus on appointing church leaders and promoting good works in Crete.",
    keyThemes: "Good Works, Church Order, Grace, Sound Doctrine, Leadership",
    sortOrder: 56,
  },
  {
    name: "Philemon",
    abbreviation: "Phlm",
    testament: "NT",
    category: "Pauline Epistles",
    chapterCount: 1,
    author: "Paul",
    dateWritten: "c. AD 60–62",
    description:
      "A personal letter requesting forgiveness and reconciliation for the runaway slave Onesimus.",
    keyThemes: "Forgiveness, Reconciliation, Brotherhood, Grace, Equality in Christ",
    sortOrder: 57,
  },

  // ─── New Testament: General Epistles ──────────────────────
  {
    name: "Hebrews",
    abbreviation: "Heb",
    testament: "NT",
    category: "General Epistles",
    chapterCount: 13,
    author: "Unknown (Paul, Apollos, or Barnabas)",
    dateWritten: "c. AD 64–68",
    description:
      "A powerful treatise on Christ's superiority over the Old Covenant, angels, Moses, and the Levitical priesthood.",
    keyThemes: "Christ's Superiority, Faith, New Covenant, Perseverance, Priesthood",
    sortOrder: 58,
  },
  {
    name: "James",
    abbreviation: "Jas",
    testament: "NT",
    category: "General Epistles",
    chapterCount: 5,
    author: "James (brother of Jesus)",
    dateWritten: "c. AD 45–49",
    description:
      "Practical wisdom for Christian living: faith in action, taming the tongue, and caring for the poor.",
    keyThemes: "Faith and Works, Wisdom, Trials, Speech, Social Justice",
    sortOrder: 59,
  },
  {
    name: "1 Peter",
    abbreviation: "1Pet",
    testament: "NT",
    category: "General Epistles",
    chapterCount: 5,
    author: "Peter",
    dateWritten: "c. AD 64–65",
    description:
      "Encouragement to suffering Christians to stand firm in faith and live holy lives as exiles.",
    keyThemes: "Suffering, Hope, Holiness, Submission, Living Hope",
    sortOrder: 60,
  },
  {
    name: "2 Peter",
    abbreviation: "2Pet",
    testament: "NT",
    category: "General Epistles",
    chapterCount: 3,
    author: "Peter",
    dateWritten: "c. AD 65–68",
    description:
      "Warnings against false teachers and encouragement to grow in knowledge of Christ while awaiting His return.",
    keyThemes: "False Teaching, Growth, Second Coming, Knowledge, Holiness",
    sortOrder: 61,
  },
  {
    name: "1 John",
    abbreviation: "1John",
    testament: "NT",
    category: "General Epistles",
    chapterCount: 5,
    author: "John (the Apostle)",
    dateWritten: "c. AD 85–95",
    description:
      "A letter on assurance of salvation through tests of faith: right belief, obedience, and love.",
    keyThemes: "Love, Fellowship, Light, Truth, Assurance",
    sortOrder: 62,
  },
  {
    name: "2 John",
    abbreviation: "2John",
    testament: "NT",
    category: "General Epistles",
    chapterCount: 1,
    author: "John (the Apostle)",
    dateWritten: "c. AD 85–95",
    description:
      "A brief letter warning against false teachers and encouraging walking in truth and love.",
    keyThemes: "Truth, Love, Discernment, False Teaching, Obedience",
    sortOrder: 63,
  },
  {
    name: "3 John",
    abbreviation: "3John",
    testament: "NT",
    category: "General Epistles",
    chapterCount: 1,
    author: "John (the Apostle)",
    dateWritten: "c. AD 85–95",
    description:
      "A personal letter commending hospitality and condemning the prideful behavior of Diotrephes.",
    keyThemes: "Hospitality, Truth, Leadership, Faithfulness, Fellowship",
    sortOrder: 64,
  },
  {
    name: "Jude",
    abbreviation: "Jude",
    testament: "NT",
    category: "General Epistles",
    chapterCount: 1,
    author: "Jude (brother of Jesus)",
    dateWritten: "c. AD 65–80",
    description:
      "An urgent call to contend for the faith against false teachers who have infiltrated the church.",
    keyThemes: "Contending for Faith, False Teachers, Judgment, Perseverance, Doxology",
    sortOrder: 65,
  },

  // ─── New Testament: Apocalyptic ───────────────────────────
  {
    name: "Revelation",
    abbreviation: "Rev",
    testament: "NT",
    category: "Apocalyptic",
    chapterCount: 22,
    author: "John (the Apostle)",
    dateWritten: "c. AD 95",
    description:
      "Apocalyptic visions of the end times: letters to seven churches, God's judgments, and the ultimate triumph of Christ.",
    keyThemes: "Second Coming, Judgment, Victory, Worship, New Heaven and Earth",
    sortOrder: 66,
  },
];
